# Generated by Django 3.2.4 on 2021-11-20 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20211120_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 22, 28, 18, 721433), null=True),
        ),
    ]
