# Generated by Django 3.2.4 on 2021-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
