# Generated by Django 3.2.4 on 2021-09-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20210914_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_address', to='hrm.address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_position', to='hrm.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_section', to='hrm.section'),
        ),
    ]
