# Generated by Django 3.2.4 on 2021-09-15 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0005_auto_20210914_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notification',
        ),
    ]
