# Generated by Django 3.2.4 on 2021-11-21 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_auto_20211121_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 18, 10, 51, 81731), null=True),
        ),
    ]
