# Generated by Django 3.2.4 on 2021-09-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_employee_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='hrm.address'),
        ),
    ]
