# Generated by Django 3.2.4 on 2021-09-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_rename_message_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
