# Generated by Django 3.2.4 on 2021-11-21 18:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0006_alter_genlink_expiration_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Info',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 18, 17, 44, 450620), null=True),
        ),
    ]
