# Generated by Django 3.2.4 on 2021-11-23 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20211122_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='home_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 49, 0, 408769), null=True),
        ),
    ]
