# Generated by Django 3.2.4 on 2021-11-23 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_auto_20211123_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 21, 38, 22, 441732), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
