# Generated by Django 3.2.4 on 2021-11-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_auto_20211124_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 12, 11, 41, 260648), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(default='https://avatars.dicebear.com/api/:sprites/:seed.svg', null=True, upload_to='images/'),
        ),
    ]
