# Generated by Django 3.2.4 on 2021-11-24 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_alter_genlink_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 18, 32, 49, 823053), null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
