# Generated by Django 3.2.4 on 2021-12-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_auto_20211124_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 11, 39, 24, 566454), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
