# Generated by Django 3.2.4 on 2021-12-03 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_auto_20211203_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 11, 41, 8, 50303), null=True),
        ),
    ]
